In [1]:
ROOT = "/content/gdrive"
from google.colab import drive
drive.mount(ROOT)

Mounted at /content/gdrive

In [19]:
import os
import yaml
import logging

PROJECT_PATH = f"{ROOT}/MyDrive/AiChan"
CONFIG_PATH = os.path.join(PROJECT_PATH, "config.yaml")

def reload_config():
  try:
    with open(CONFIG_PATH, "r", encoding='utf-8') as f:
      config = yaml.safe_load(f)
  except FileNotFoundError as e:
    logging.error("Error: ", e)
    raise FileNotFoundError(e) from e
  return config

CONFIG = reload_config()

In [9]:
import pandas as pd
LIST_PATH = ROOT + CONFIG['PROJECT']['DATA']['GRAMMAR']['LIST']
df = pd.read_csv(LIST_PATH)
df.head(10)

,N5,1,ちゃいけない・じゃいけない,cha ikenai / ja ikenai,must not do (spoken Japanese),Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,source: https://jlptsensei.com
0,N5,2,だ・です,da / desu,"to be (am, is, are, were, used to)",NaN,NaN,NaN,NaN,NaN,NaN
1,N5,3,だけ,dake,only; just; as much as,NaN,NaN,NaN,NaN,NaN,NaN
2,N5,4,だろう,darou,I think; it seems; probably; right?,NaN,NaN,NaN,NaN,NaN,NaN
3,N5,5,で,de,in; at; on; by; with; via,NaN,NaN,NaN,NaN,NaN,NaN
4,N5,6,でも,demo,but; however,NaN,NaN,NaN,NaN,NaN,NaN
5,N5,7,でしょう,deshou,I think; it seems; probably; right?,NaN,NaN,NaN,NaN,NaN,NaN
6,N5,8,どんな,donna,what kind of; what sort of,NaN,NaN,NaN,NaN,NaN,NaN
7,N5,9,どうして,doushite,why; for what reason; how,NaN,NaN,NaN,NaN,NaN,NaN
8,N5,10,どうやって,douyatte,how; in what way; by what means,NaN,NaN,NaN,NaN,NaN,NaN
9,N5,11,が,ga,subject marker; however; but,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df_copy = df.copy().iloc[:, :5]
df_copy.columns = ['level', 'num', 'sfld', 'romanji', 'mean']
df_copy.drop('num', axis=1, inplace=True)
df_copy.head(10)

  level   sfld       kana                                 mean
0    N5   だ・です  da / desu   to be (am, is, are, were, used to)
1    N5     だけ       dake               only; just; as much as
2    N5    だろう      darou  I think; it seems; probably; right?
3    N5      で         de            in; at; on; by; with; via
4    N5     でも       demo                         but; however
5    N5   でしょう     deshou  I think; it seems; probably; right?
6    N5    どんな      donna           what kind of; what sort of
7    N5   どうして   doushite            why; for what reason; how
8    N5  どうやって   douyatte      how; in what way; by what means
9    N5      が         ga         subject marker; however; but

In [21]:
df_copy.shape

(830, 4)

In [20]:
SAVE_PATH = ROOT + CONFIG['PROJECT']['DATA']['GRAMMAR']['SAVE']
df_copy.to_csv(SAVE_PATH)